version: 'latest'
services:
  django-app:
    image: hangman
    build: 
      context: .
    deploy:
      resources:
        limits:
          memory: 4g
          cpus: "2.0"
    ports:
      - 8000:8000