apiVersion: apps/v1
kind: Deployment
metadata:
  name: hangman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hangman
  template:
    metadata:
      labels:
        app: hangmna
    spec:
      containers:
      - name: hangman
        image: hangman:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        args:
          - -cpus
          - "2"
        ports:
        - containerPort: 8000
